
name: catch_the_emoji
description: A fun reflex-testing game built in Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hit.mp3
    - assets/miss.mp3
